import { Montserrat } from 'next/font/google'
import './globals.css'
import FakeNav from '@/components/NavBar/FakeNav'

const font = Montserrat({ weight: ['400'], subsets: ['latin'] })

export const metadata = {
	title: 'Nube Menu',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={font.className}>
				{/* <FakeNav /> */}
				{children}
			</body>
		</html>
	)
}
